### ISSUE TITLE
祝贺作出优秀的工作

### ISSUE THREAD

**Issue by caiyuanhao1998** [YhuoyuH/RetinexMamba#1]
感谢作者的努力作出优秀的工作

我注意到这是基于我们的retinexformer做的，不知是否方便也acknowledge 一下我们的 repo 为代码的来源呢🤣，创作不易，感谢

**Comment by caiyuanhao1998** [comment]
以及帮忙点点star支持一下，感谢🙏

**Comment by YhuoyuH** [comment]
感谢您为开源社区做出的贡献，我们现在已经在README的最后部分加上了仓库地址：
@inproceedings{Retinexformer,   title={Retinexformer: One-stage Retinex-based Transformer for Low-light Image Enhancement},   author={Yuanhao Cai and Hao Bian and Jing Lin and Haoqian Wang and Radu Timofte and Yulun Zhang},   booktitle={ICCV},   year={2023},   reposittory:https://github.com/caiyuanhao1998/Retinexformer }
不知是否符合您的要求呢，如需要进一步修改烦请您联系我，感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YhuoyuH/RetinexMamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 中午11:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YhuoyuH/RetinexMamba] 祝贺作出优秀的工作 (Issue #1)





 
感谢作者的努力作出优秀的工作
 
我注意到这是基于我们的retinexformer做的，不知是否方便也acknowledge 一下我们的 repo 为代码的来源呢🤣，创作不易，感谢

**Comment by caiyuanhao1998** [comment]
好的，感谢🙏

**Comment by caiyuanhao1998** [comment]
hello, 好像这个改得不对，bibtex可以发麻烦改回去吗？

然后在 acknowledge 的最下面写上

This repo is based on [Retinexformer](https://github.com/caiyuanhao1998/Retinexformer) (ICCV 2023)

这样子比较正规一些，感谢

**Comment by YhuoyuH** [comment]
ok，已经改好了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yuanhao Cai ***@***.***&gt;
发送时间: 2024年5月13日 09:36
收件人: YhuoyuH/RetinexMamba ***@***.***&gt;
抄送: YhuoyuH ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [YhuoyuH/RetinexMamba] 祝贺作出优秀的工作 (Issue #1)





 
hello, 好像这个改得不对，bibtex可以发麻烦改回去吗？
 
然后在 acknowledge 的最下面写上
 
This repo is based on Retinexformer (ICCV 2023)
 
这样子比较正规一些，感谢

**Comment by caiyuanhao1998** [comment]
感谢。不过 Retinexformer 和 (ICCV 2023) 之间少了一个空格。

我在我的 repo 里面也写了一个指向你们 repo 的 link 来帮你们引流，预祝投稿顺利

<img width="877" alt="截屏2024-05-12 下午10 04 07" src="https://github.com/YhuoyuH/RetinexMamba/assets/48472661/6bc67c50-5303-4b3f-ba0d-5f2e78d242a9">

**Comment by YhuoyuH** [comment]
已修改完成。
感谢指导，借您吉言





------------------ 原始邮件 ------------------
发件人: Yuanhao Cai ***@***.***&gt;
发送时间: 2024年5月13日 10:04
收件人: YhuoyuH/RetinexMamba ***@***.***&gt;
抄送: YhuoyuH ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [YhuoyuH/RetinexMamba] 祝贺作出优秀的工作 (Issue #1)





 
感谢。不过 Retinexformer 和 (ICCV 2023) 之间少了一个空格。
 
我在我的 repo 里面也写了一个指向你们 repo 的 link 来帮你们引流，预祝投稿顺利
 2024-05-12.10.04.07.png (view on web)
