### ISSUE TITLE
训练gpu数量

### ISSUE THREAD

**Issue by russellllaputa** [YhuoyuH/RetinexMamba#2]
非常感谢作者的开源。 
想请问作者在LOL数据集上，是用多少个GPU进行训练的啊？ 以及GPU型号也麻烦告知一下。

**Comment by YhuoyuH** [comment]
您好，我们在训练时只用了一个24g的GPU，型号已经在实验部分写了哦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Laputa ***@***.***&gt;
发送时间: 2024年5月14日 18:33
收件人: YhuoyuH/RetinexMamba ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [YhuoyuH/RetinexMamba] 训练gpu数量 (Issue #2)





 
非常感谢作者的开源。
 想请问作者在LOL数据集上，是用多少个GPU进行训练的啊？ 以及GPU型号也麻烦告知一下。
